### PR TITLE
Add tcell to support Windows

### PR DESCRIPTION
**Pull request by markruler**
image

image

But it doesn't work properly. I need help with this PR.

### CODE REVIEW

**Comment by nakabonne** [comment]
@markruler Hi, thanks for your contribution! To be honest, I've been putting off anything related to Windows for a long time. I'm not able to set up a Windows environment right away, so please be patient! (will probably start on it this weekend)

**Comment by nakabonne** [comment]
@markruler We need to discuss this before implementing it, so could you please open a new issue with the screenshot?

**Comment by nakabonne** [comment]
I just opened a new issue https://github.com/nakabonne/ali/issues/62

**Comment by brenol** [comment]
Hi @markruler,

Just used your branch with Powershell and it looks like this:
image

Using cmd.exe inside Windows Terminal, redraw is quite slow (and I can see it "moving from upwards to the bottom"), but it actually works OK IMO:
image

I'm using Windows terminal on 20231 pre_release (Insider fast build).

I feel like its improved on new releases (like the build I'm using) but I'm not sure. Windows Terminal version is 1.3.2651.0.

Perhaps a new release will fix this?

**Comment by markruler** [comment]
Thanks for your review! @brenol
Yes, my terminal version is `1.3.2651.0`. And I tried to install Windows 10 on the Hyper-V, but there was nothing wrong.

image

I think this is a problem that happened when I customized the terminal. But I still don't know exactly why this problem happened.

**Comment by markruler** [comment]
I've figured out the cause. It's because of the **font**.

@nakabonne 
Could you merge this PR?

image

**Review by nakabonne — APPROVED** [review]
I see that it may not render correctly with some font settings. It doesn't seem to be a problem, so I'll be happy to merge it.

@markruler Thanks for your help!

**Comment by nakabonne** [comment]
@brenol Thanks for helping me with my review!

**Pull request merged**
