### PR TITLE
moves uint64 on struct top

### PR DESCRIPTION
**Pull request by xsteadfastx**
i added ali as apk package for alpine linux. we discovered that it failed on 32 bit arches. this is a try to fix this.

### CODE REVIEW

**Comment by xsteadfastx** [comment]
here are the logs from the build servers: https://gitlab.alpinelinux.org/alpine/aports/-/jobs/463920

**Comment by nakabonne** [comment]
Hi, does the fixed-length type have to be on the top of struct fields? I didn't even know that but it's a tiny change, let's merge it.

**Comment by xsteadfastx** [comment]
On Mo, 16. Aug 18:59, Ryo Nakao wrote:
> Hi, does the fixed-length type have to be on the top of struct fields? I didn't even know that but it's a tiny change, let's merge it.

i just found out about it, googling around. i tried it because of this: https://pkg.go.dev/sync/atomic#pkg-note-BUG

**Comment by xsteadfastx** [comment]
On Di, 17. Aug 00:00, Ryo Nakao wrote:
> That makes sense. I learned something new, thank you!

and thank you for your wonderful piece of software!

**Pull request merged**
